### ISSUE TITLE
Implement Heap Sorting Technique [using HEAP Data structure]

### ISSUE THREAD

**Issue by ankit-95** [LorenzNickel/java-fundamentals#52]
**Is your feature request related to a problem? Please describe.**
I want to contribute to sorting by implementing Heap Sort.

**Describe the solution you'd like**
I will be implementing Heap sort with proper indentation so that it will be easy to understand.
This solution will use Max Heap to implement the sorting.

**Additional context**
@LorenzNickel. Please assign this issue to me.

**Comment by LorenzNickel** [comment]
Hey @ankit-95,

it looks like HeapSort has already been implemented in this repository.
It's not part of the [java-fundamentals/src/main/java/algorithms/sort/-package](https://github.com/LorenzNickel/java-fundamentals/tree/master/src/main/java/algorithms/sort), where you probably looked for it, but instead, it's implemented [here ](https://github.com/LorenzNickel/java-fundamentals/blob/master/src/main/java/datastructures/heap/MinArrayHeap.java)and [here](https://github.com/LorenzNickel/java-fundamentals/blob/master/src/main/java/datastructures/heap/MaxArrayHeap.java).
